[package]
name = "anienc-next"
version = "0.1.0"
edition = "2021"
authors = ["flippette <quangdatle2006@outlook.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
eyre = "0.6"
color-eyre = "0.6"
log = "0.4"
femme = "2.2"
ffmpeg = { version = "6.0", package = "ffmpeg-next" }
glob = "0.3"
