#!/bin/sh

# `set -o pipefail` is in POSIX.1-2024
# shellcheck disable=SC3040
set -euo pipefail

# disable word splitting on space
IFS=$(printf "\n\t")

query() {
  file=$1
  stream=$2
  ffprobe \
    -v quiet \
    -show_streams \
    -select_streams "$stream" \
    "$file"
}

if [ $# -eq 0 ]; then
  files="./*"
else
  files=$*
fi

svtav1_preset=2
svtav1_params=$(
  printf %s \
    'psy-rd=1.0' \
    ':complex-hvs=1' \
    ':hbd-mds=1' \
    ':enable-dlf=2' \
    ':noise-adaptive-filtering=4' \
    ":lp=$(nproc)"
)

for file in $files; do
  printf %s\\n "checking file $file"
  if [ -z "$(query "$file" v)" ]; then
    printf %s\\n "file $file is missing video stream"
    continue
  elif [ -z "$(query "$file" a:m:language:jpn)" ]; then
    printf %s\\n "file $file is missing jpn audio stream"
    continue
  elif [ -z "$(query "$file" s:m:language:eng)" ]; then
    printf %s\\n "file $file is missing eng subtitle stream"
    continue
  fi
  printf %s\\n "file $file is valid"

  printf %s\\n "probing file $file"
  crf=$(
    # Experimenting with Sousou no Frieren shows that
    # XPSNR 39.5 roughly equals VMAF 94 to 95.5. YMMV.
    ab-av1 crf-search \
      -i "$file" \
      --pix-format yuv420p10le \
      --preset "$svtav1_preset" \
      --enc-input hwaccel=auto \
      --svt "$svtav1_params" \
      --min-xpsnr 39.5 \
      --thorough | rg predicted | cut -d ' ' -f 2
  )
  if [ "$crf" = "" ]; then
    crf=40
  fi
  printf %s\\n "using crf $crf for file $file"

  printf %s\\n "encoding file $file"
  ffmpeg \
    -hwaccel auto \
    -i "$file" \
    -pix_fmt yuv420p10le \
    -c:v libsvtav1 \
    -b:v 0 \
    -crf "$crf" \
    -preset "$svtav1_preset" \
    -svtav1-params "$svtav1_params" \
    -c:a libopus \
    -b:a 160k \
    -c:s copy \
    -map 0:V \
    -map 0:a:m:language:jpn \
    -map 0:s:m:language:eng \
    "${file%.*}.enc.mkv"
  printf %s\\n "finished encoding file $file"
done
