#!/usr/bin/bash

# global variables
prefix="./op/hevc"

# prepare directories
rm -rf $prefix
mkdir -p $prefix

for file in *.mkv; do
  ffmpeg \
    -i $file \
    -c:v libx265 \
    -pix_fmt yuv420p10le \
    -profile:v main10 \
    -x265-params "\
      aq-mode=3\
      :psy-rd=1\
      :aq-strength=0.8\
      :deblock=0,0\
      :bframes=8\
    " \
    -b:v 0 \
    -crf 23 \
    -preset veryslow \
    \
    -c:a libopus \
    -b:a 128k \
    \
    -map 0:v \
    -map 0:a:m:language:jpn \
    -map 0:s:m:language:eng \
    "${prefix}/${file}"
done
