[package]
name = "anienc"
version = "0.1.0"
edition = "2021"
authors = ["flippette <quangdatle2006@outlook.com>"]
license = "WTFPL"

[dependencies]
eyre = "0.6"
tracing = "0.1"
camino = "1.1"
color-eyre = "0.6"
tracing-subscriber = "0.3"
glob = "0.3"
